// Copyright 2018-2024 go-m3ua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package m3ua

import (
	"errors"
	"fmt"
	"net"
	"time"

	"github.com/gomaja/go-m3ua/messages/params"
	"github.com/gomaja/go-sctp"
)

// HeartbeatInfo configures RFC 4666 M3UA BEAT/BEAT Ack liveness.
//
// It does not configure SCTP HEARTBEAT chunks or SCTP path-management timers;
// those stay in the SCTP transport stack. This package uses HeartbeatInfo only
// for application-layer ASPSM BEAT messages after the ASP reaches ASP-ACTIVE.
type HeartbeatInfo struct {
	// Enabled turns on the managed M3UA BEAT loop.
	Enabled bool
	// Interval is T(beat), the delay before sending the next M3UA BEAT.
	Interval time.Duration
	// Timer is the M3UA liveness deadline for a BEAT round. Zero resolves to
	// 2*T(beat), per RFC 4666 Section 4.3.4.6.
	Timer time.Duration
	// Data is retained for API compatibility. The managed BEAT loop ignores this
	// field and sends fresh opaque Heartbeat Data each round so BEAT Acks can be
	// matched and replay attempts rejected.
	Data []byte
}

// NewHeartbeatInfo creates M3UA BEAT configuration.
//
// The data argument is retained in the returned HeartbeatInfo for API
// compatibility, but the managed BEAT loop generates fresh Heartbeat Data for
// every transmitted M3UA BEAT.
func NewHeartbeatInfo(interval, timer time.Duration, data []byte) *HeartbeatInfo {
	return &HeartbeatInfo{
		Enabled: true, Interval: interval, Timer: timer, Data: data,
	}
}

// SCTPSACKInfo configures the SCTP delayed-SACK timer.
//
// SackDelay sack_delay: This parameter contains the number of milliseconds the
// user is requesting that the delayed SACK timer be set to.
//
// RFC 9260 Section 6.2 — the current SCTP specification, which obsoleted
// RFC 4960 — bounds it from above only: "An implementation MUST NOT allow the
// maximum delay (protocol parameter 'SACK.Delay') to be configured to be more
// than 500 ms. In other words, an implementation MAY lower the value of
// 'SACK.Delay' below 500 ms but MUST NOT raise it above 500 ms." The 200 ms in
// the same section is when an acknowledgement SHOULD be generated by, not a
// floor, so any value up to 500 is permitted and zero disables the delay.
// A larger value is refused when the association is set up; see
// ErrSackDelayTooLarge.
//
// SackFrequency sack_freq: This parameter contains the number of packets that must
// be received before a SACK is sent without waiting for the delay
// timer to expire.  The default value is 2; setting this value to 1
// will disable the delayed SACK algorithm.
type SCTPSACKInfo struct {
	Enabled       bool
	SackDelay     uint32
	SackFrequency uint32
}

// SCTPNoDelayInfo is a set of information for SCTP NODELAY configuration.
//
// NoDelay, when true, disables the Nagle-like bundling algorithm so that
// user messages are sent as soon as possible (SCTP_NODELAY = 1). When
// false, small messages may be bundled to improve throughput.
type SCTPNoDelayInfo struct {
	Enabled bool
	NoDelay bool
}

// DefaultReadBufferSize is the read buffer size used when SCTPConfig
// leaves ReadBufferSize unset.
//
// 64 KiB accommodates any M3UA message in practical use — SS7 traffic
// interworked at an SG is capped at a 272-octet SIF, and even the larger blocks
// M3UA permits natively stay far below this — while costing one allocation per
// association rather than per read.
const DefaultReadBufferSize = 65535

// SCTPConfig holds all SCTP-related configuration parameters.
// This separates SCTP layer configuration from M3UA layer configuration.
//
// An AssociationConfig — and therefore its SCTPConfig — may be shared by every
// association a Listener
// accepts, and by repeated Dials. It therefore holds settings only: the
// SCTP association and everything derived from it belong to the Association.
type SCTPConfig struct {
	*SCTPSACKInfo
	*SCTPNoDelayInfo

	// InitTimeout bounds Dial's one-shot SCTP association attempt. Zero
	// selects DefaultInitTimeout.
	InitTimeout time.Duration

	// ReadBufferSize is the size of the buffer each read from the association
	// is made into. Zero selects DefaultReadBufferSize.
	//
	// SCTP reassembles a fragmented message before delivering it, so this is
	// not an MTU: it must accommodate the largest single M3UA message a peer
	// may send. RFC 4666 Section 1.3.2.1 is explicit that "The M3UA layer does
	// not impose a 272-octet signalling information field (SIF) length limit
	// as specified by the SS7 MTP Level 2 protocol. Larger information blocks
	// can be accommodated directly by M3UA/SCTP", and the message length field
	// is 32-bit, so there is no protocol-level maximum to size against. Raise
	// this if a peer is known to send larger blocks than the default allows.
	ReadBufferSize int
}

// DefaultInitTimeout bounds one SCTP association attempt: how long Dial waits
// for the INIT-ACK before giving up and releasing the socket.
//
// Dial makes at most one attempt and never retries; a caller that wants to keep
// trying loops over Dial and chooses its own cadence. Left to the kernel, the
// attempt runs to net.sctp.max_init_retransmits with the RTO doubling from
// net.sctp.rto_initial to net.sctp.rto_max — measured at nine INIT chunks over
// 342 seconds on Linux defaults, which is far too long for an application to
// react to anything.
//
// Dial enforces the one-shot contract per socket by raising SCTP_RTOINFO's
// Initial and Max values beyond this budget before connecting. If no INIT-ACK
// arrives before the timeout, Dial returns ErrInitTimeout; if ctx is cancelled
// first, Dial quietly abandons the in-flight socket promptly and returns
// ctx.Err().
const DefaultInitTimeout = 5 * time.Second

// DefaultEstablishTimeout bounds the M3UA handshake once the association is up:
// how long Dial and Accept wait to reach ASP-ACTIVE.
const DefaultEstablishTimeout = 10 * time.Second

// DefaultDataQueueSize is the number of inbound DATA messages one association
// retains while its application is not reading. It is large enough to absorb
// ordinary traffic bursts without the 65,535-slot allocation every Association used
// to make; sustained overflow remains non-blocking and reports local congestion.
const DefaultDataQueueSize = 1024

// DefaultRecoveryQueueMessages bounds how many outbound DATA messages an SGP
// retains while an Application Server is AS-PENDING. RFC 4666 Section 4.3.2
// recommends queuing during T(r), but an unbounded queue lets a failed AS
// exhaust the process before recovery can complete.
const DefaultRecoveryQueueMessages = 1024

// DefaultRecoveryQueueBytes bounds the encoded size of the DATA messages held
// for one AS during T(r). The count limit alone is insufficient because M3UA
// deliberately permits payloads larger than an SS7 MTP2 SIF.
const DefaultRecoveryQueueBytes = 4 << 20

// DefaultRecoveryQueueTotalMessages bounds recovery DATA retained across all
// Application Servers owned by one SGP Endpoint.
const DefaultRecoveryQueueTotalMessages = 4096

// DefaultRecoveryQueueTotalBytes is the SGP Endpoint-wide encoded DATA budget.
const DefaultRecoveryQueueTotalBytes = 16 << 20

// DefaultBroadcastFlowCacheEntries bounds synchronization markers retained for
// one Broadcast AS. Eviction can only cause an extra Correlation ID to be sent.
const DefaultBroadcastFlowCacheEntries = 4096

// DefaultBroadcastFlowIdentifierBytes bounds the application-defined portion
// of a retained Broadcast flow key.
const DefaultBroadcastFlowIdentifierBytes = 256

// DefaultTAckRetries is how many times an unacknowledged ASPSM/ASPTM request is
// resent before the attempt is reported as failed.
//
// RFC 4666 says to resend "until it receives the Ack", which is unbounded; a
// bound turns a peer that will never answer into a reportable error instead of
// an indefinite silent retry against a network already in trouble.
const DefaultTAckRetries = 5

// BroadcastFlowIdentifier adds application semantics to the default Broadcast
// traffic-flow key. The library already keys by Network Appearance, Routing
// Context, and the complete MTP3 routing label. Applications may return, for
// example, an ISUP CIC or SCCP subsystem discriminator when independently
// sequenced flows share that label. The callback receives an owned copy and
// must return a stable identifier for equivalent flows.
type BroadcastFlowIdentifier func(*params.ProtocolDataPayload) (string, error)

// ASActivationPolicy configures the n+k activation threshold of one
// Application Server.
//
// RFC 4666 Sections 1.4.4.1 and 4.3.2 define RequiredActiveASPs as n. Zero
// selects one. SmoothStart enables the Section 4.3.2 exception that permits
// the first active ASP to start traffic before n ASPs are active.
type ASActivationPolicy struct {
	RequiredActiveASPs int
	SmoothStart        bool
}

func (p ASActivationPolicy) requiredActive() int {
	if p.RequiredActiveASPs == 0 {
		return 1
	}
	return p.RequiredActiveASPs
}

// ApplicationServerConfig configures Application Server state shared by all
// Associations owned by one SGP or IPSP Endpoint.
type ApplicationServerConfig struct {
	// RecoveryTimer is T(r), the AS-PENDING recovery timer of RFC 4666
	// Section 4.3.2. Zero selects DefaultRecoveryTimer.
	RecoveryTimer time.Duration
	// DefaultActivationPolicy applies when ActivationPolicies has no exact
	// ASKey entry.
	DefaultActivationPolicy ASActivationPolicy
	// ActivationPolicies configures n and smooth start for exact Application
	// Server traffic identities. The map is deeply copied by NewEndpoint.
	ActivationPolicies map[ASKey]ASActivationPolicy
}

// SGPConfig configures protocol state shared by every Association owned by one
// Signalling Gateway Process Endpoint.
//
// RFC 4666 Sections 4.3.2, 4.3.4.3, and 4.6 define recovery queuing,
// distribution, and restart procedures in terms of an SGP and its Application
// Servers, not in terms of one SCTP association or the peer that initiated it.
type SGPConfig struct {
	// RecoveryQueueMessages and RecoveryQueueBytes bound DATA retained for one
	// AS while T(r) runs. Values less than or equal to zero select defaults.
	RecoveryQueueMessages int
	RecoveryQueueBytes    int
	// RecoveryQueueTotalMessages and RecoveryQueueTotalBytes bound retained DATA
	// across every AS owned by the SGP Endpoint.
	RecoveryQueueTotalMessages int
	RecoveryQueueTotalBytes    int
	// BroadcastFlowIdentifier refines the default routing-label flow key used
	// for RFC 4666 Section 4.3.4.3 Broadcast synchronization Correlation IDs.
	BroadcastFlowIdentifier BroadcastFlowIdentifier
	// BroadcastFlowCacheEntries bounds remembered flows per AS. Values less than
	// or equal to zero select DefaultBroadcastFlowCacheEntries.
	BroadcastFlowCacheEntries int
	// BroadcastFlowIdentifierBytes bounds an application-defined flow
	// identifier. Values less than or equal to zero select the default.
	BroadcastFlowIdentifierBytes int
}

// IPSPExchangeModel identifies the peer-to-peer exchange model used by one
// IPSP Association. RFC 4666 Section 4.3 defines Single Exchange and Double
// Exchange independently of which IPSP initiates the SCTP association.
type IPSPExchangeModel uint8

const (
	// IPSPExchangeSingle is the mandatory Single Exchange model of RFC 4666
	// Sections 4.3 and 5.6.1. One ASPSM or ASPTM request-and-ack exchange
	// changes the state maintained by both IPSPs.
	IPSPExchangeSingle IPSPExchangeModel = iota + 1
	// IPSPExchangeDouble is the optional Double Exchange model of RFC 4666
	// Sections 4.3 and 5.6.2. Its independent directional state is implemented
	// separately from Single Exchange.
	IPSPExchangeDouble
)

// IPSPASPSMExchangeModel identifies the ASPSM procedure agreed for an IPSP
// Double Exchange Association. RFC 4666 Section 4.3 defines the normal double
// exchange and permits a single exchange as an agreed simplification.
type IPSPASPSMExchangeModel uint8

const (
	// IPSPASPSMExchangeDouble keeps the two IPSP ASPSM directions independent.
	IPSPASPSMExchangeDouble IPSPASPSMExchangeModel = iota + 1
	// IPSPASPSMExchangeSingle lets one ASP Up or ASP Down exchange affect the
	// whole IPSP communication, as permitted by RFC 4666 Sections 4.3 and 5.6.2.
	IPSPASPSMExchangeSingle
)

// IPSPTrafficConfig configures one direction of IPSP Double Exchange traffic.
// RoutingContexts identify the Routing Keys for that direction, while Network
// Appearance and Traffic Mode apply only to those traffic flows.
type IPSPTrafficConfig struct {
	TrafficModeType   *params.Param
	TrafficModes      map[uint32]uint32
	NetworkAppearance *params.Param
	RoutingContexts   *params.Param
}

// IPSPConfig configures RFC 4666 peer-to-peer procedures for one Association.
//
// InitiateASPSM and InitiateASPTM select whether this IPSP automatically starts
// the initial procedure of the named class. Either IPSP may initiate each
// exchange, and the choices are independent from SCTP association initiation.
type IPSPConfig struct {
	ExchangeModel IPSPExchangeModel
	// ASPSMExchange is the ASPSM agreement for Double Exchange. It is not
	// used by Single Exchange.
	ASPSMExchange IPSPASPSMExchangeModel
	// InitiateASPSM starts this IPSP's ASP Up procedure independently of SCTP
	// association initiation. Normal Double Exchange requires TrafficToLocal;
	// the agreed single-ASPSM simplification may establish both directions. A
	// non-nil AssociationConfig.ASPProcedures policy supersedes this flag.
	InitiateASPSM bool
	// InitiateASPTM starts this IPSP's ASP Active procedure after its local
	// ASPSM direction becomes ASP-INACTIVE. A non-nil
	// AssociationConfig.ASPProcedures policy supersedes this flag.
	InitiateASPTM bool
	// TrafficToLocal configures DATA the peer sends to this IPSP.
	TrafficToLocal *IPSPTrafficConfig
	// TrafficToPeer configures DATA this IPSP sends to the peer.
	TrafficToPeer *IPSPTrafficConfig
}

// EndpointConfig gives one M3UA Endpoint its immutable RFC 4666 role and any
// role-specific node policy.
type EndpointConfig struct {
	Role                 Role
	ASP                  *ASPConfig
	SGP                  *SGPConfig
	ApplicationServers   *ApplicationServerConfig
	RoutingKeyManagement *RoutingKeyManagementConfig
}

func validateApplicationServerConfig(config *ApplicationServerConfig) error {
	if config == nil {
		return nil
	}
	if config.RecoveryTimer < 0 {
		return fmt.Errorf("%w: negative RecoveryTimer", ErrInvalidApplicationServerConfig)
	}
	if config.DefaultActivationPolicy.RequiredActiveASPs < 0 {
		return fmt.Errorf("%w: negative default RequiredActiveASPs", ErrInvalidApplicationServerConfig)
	}
	for key, policy := range config.ActivationPolicies {
		if !key.NetworkAppearanceSet && key.NetworkAppearance != 0 {
			return fmt.Errorf("%w: Network Appearance %d is present without NetworkAppearanceSet",
				ErrInvalidApplicationServerConfig, key.NetworkAppearance)
		}
		if !key.RoutingContextSet && key.RoutingContext != 0 {
			return fmt.Errorf("%w: Routing Context %d is present without RoutingContextSet",
				ErrInvalidApplicationServerConfig, key.RoutingContext)
		}
		if policy.RequiredActiveASPs < 0 {
			return fmt.Errorf("%w: negative RequiredActiveASPs for %+v",
				ErrInvalidApplicationServerConfig, key)
		}
	}
	return nil
}

func snapshotApplicationServerConfig(config *ApplicationServerConfig) *ApplicationServerConfig {
	if config == nil {
		return &ApplicationServerConfig{}
	}
	snapshot := *config
	if config.ActivationPolicies != nil {
		snapshot.ActivationPolicies = make(map[ASKey]ASActivationPolicy, len(config.ActivationPolicies))
		for key, policy := range config.ActivationPolicies {
			snapshot.ActivationPolicies[key] = policy
		}
	}
	return &snapshot
}

func applicationServerActivationPolicy(config *ApplicationServerConfig, key ASKey) ASActivationPolicy {
	if config == nil {
		return ASActivationPolicy{}
	}
	if policy, ok := config.ActivationPolicies[key]; ok {
		return policy
	}
	return config.DefaultActivationPolicy
}

func validateApplicationServerRoutingKeyPolicies(
	applicationServers *ApplicationServerConfig,
	routingKeys *RoutingKeyManagementConfig,
) error {
	if routingKeys == nil {
		return nil
	}
	for _, provisioned := range routingKeys.ProvisionedRoutingKeys {
		if !provisioned.RoutingKey.TrafficModeSet ||
			provisioned.RoutingKey.TrafficMode != params.TrafficModeOverride {
			continue
		}
		key := ASKey{
			NetworkAppearance:    provisioned.RoutingKey.NetworkAppearance,
			NetworkAppearanceSet: provisioned.RoutingKey.NetworkAppearanceSet,
			RoutingContext:       provisioned.RoutingContext,
			RoutingContextSet:    true,
		}
		if applicationServerActivationPolicy(applicationServers, key).requiredActive() != 1 {
			return fmt.Errorf("%w: Override requires one active ASP for %+v",
				ErrInvalidApplicationServerConfig, key)
		}
	}
	return nil
}

func snapshotSGPConfig(config *SGPConfig) *SGPConfig {
	if config == nil {
		return &SGPConfig{}
	}
	snapshot := *config
	return &snapshot
}

// ASPIdentity identifies an ASP at the point its ASP Up is received. The ASP
// Identifier is optional in RFC 4666, so ASPIdentifierSet distinguishes an
// omitted identifier from the valid value zero. RemoteAddr is nil for an Association
// constructed without a live SCTP association.
type ASPIdentity struct {
	ASPIdentifier    uint32
	ASPIdentifierSet bool
	RemoteAddr       net.Addr
}

// ASPAuthorizer returns the Routing Contexts an accepted ASP is configured to
// serve. The result is copied and must be a subset of
// AssociationConfig.RoutingContexts.
// Returning an empty slice authorizes no Application Server. The decision is
// resolved once at ASP Up and remains immutable for that association.
type ASPAuthorizer func(ASPIdentity) []uint32

// AssociationConfig configures one M3UA association.
//
// A Listener owns the shared SCTP listening socket; each accepted SCTP
// association uses an immutable AssociationConfig snapshot selected by
// ListenerConfig before any M3UA message is parsed.
type AssociationConfig struct {
	// HeartbeatInfo controls M3UA BEAT/BEAT Ack liveness only; it is separate
	// from SCTP HEARTBEAT path management.
	*HeartbeatInfo
	*SCTPConfig
	// TAck is the T(ack) timer: how long to wait for an ASPSM/ASPTM
	// acknowledgement before resending the request. Zero selects DefaultTAck
	// (2 seconds, per RFC 4666 Sections 4.3.4.1 to 4.3.4.4).
	TAck time.Duration
	// TAckRetries bounds how many times a request is resent before the attempt
	// is reported as failed. Zero selects DefaultTAckRetries.
	TAckRetries int
	// EstablishTimeout bounds the M3UA handshake once the association is up.
	// Zero selects DefaultEstablishTimeout.
	EstablishTimeout time.Duration
	// DataQueueSize is the maximum number of inbound DATA messages retained for
	// Read, ReadPD, or ReadData. Values less than or equal to zero select
	// DefaultDataQueueSize. Once full, further DATA is discarded and local
	// congestion is reported without blocking the association dispatcher.
	DataQueueSize int
	ASPIdentifier *params.Param
	// TrafficModeType is the default traffic-handling mode. Its value is copied
	// when an Association or Listener is constructed; later mutations do not
	// alter established protocol policy.
	TrafficModeType *params.Param
	// AuthorizeASP optionally narrows this accepted Association's configured
	// Routing Context inventory to the immutable set its peer ASP may serve.
	// Without it, the peer ASP may serve every configured Routing Context.
	AuthorizeASP ASPAuthorizer
	// TrafficModes optionally configures Traffic Mode per Routing Context. It
	// takes precedence over TrafficModeType and permits one association to serve
	// ASes with different modes. Values must be Override, Loadshare, or Broadcast.
	// The map is copied when an Association or Listener is constructed.
	TrafficModes      map[uint32]uint32
	NetworkAppearance *params.Param
	// Compatibility configures explicit receive-side tolerance for known peer
	// protocol violations. The zero value keeps RFC-strict behaviour.
	Compatibility CompatibilityPolicy
	// ASPProcedures selects automatic or explicit Layer Management initiation
	// for ASP Up, ASP Down, ASP Active, and ASP Inactive. A nil policy preserves
	// the historical role-specific lifecycle. A non-nil policy fully supersedes
	// IPSPConfig.InitiateASPSM and IPSPConfig.InitiateASPTM.
	ASPProcedures *ASPProcedurePolicy
	// PeerSGP identifies the remote Signalling Gateway Process for an
	// Association owned by an ASP Endpoint. It is invalid for an SGP Endpoint.
	PeerSGP *SGPIdentity
	// IPSP is required for an Association owned by an IPSP Endpoint and invalid
	// for ASP and SGP Endpoints. The exchange model is Association policy: one
	// IPSP may use different models with different peers.
	IPSP *IPSPConfig

	RoutingContexts         *params.Param
	CorrelationID           *params.Param
	OriginatingPointCode    uint32
	DestinationPointCode    uint32
	ServiceIndicator        uint8
	NetworkIndicator        uint8
	MessagePriority         uint8
	SignallingLinkSelection uint8
}

// AcceptInfo identifies an SCTP association before its M3UA handshake starts.
//
// The addresses are owned copies of the SCTP addresses returned by the
// association so a selector can inspect or retain full multi-homing data
// without mutating transport-owned address objects.
type AcceptInfo struct {
	LocalAddr  *sctp.SCTPAddr
	RemoteAddr *sctp.SCTPAddr
}

// AssociationConfigSelector chooses the immutable AssociationConfig for an
// accepted SCTP association.
type AssociationConfigSelector func(AcceptInfo) (*AssociationConfig, error)

// ListenerConfig configures a shared M3UA listener.
//
// DefaultAssociationConfig is the fallback per-association configuration. If
// SelectAssociationConfig is set, it runs after SCTP accept and before socket
// options, monitor goroutines, ASP Up parsing, or compatibility handling.
type ListenerConfig struct {
	DefaultAssociationConfig *AssociationConfig
	SelectAssociationConfig  AssociationConfigSelector
}

// NewListenerConfig creates a listener configuration with an immutable default
// AssociationConfig snapshot.
func NewListenerConfig(defaultAssociationConfig *AssociationConfig) *ListenerConfig {
	if defaultAssociationConfig == nil {
		defaultAssociationConfig = NewAssociationConfig(0, 0, 0, 0, 0, 0)
	}
	return &ListenerConfig{
		DefaultAssociationConfig: snapshotAssociationConfig(defaultAssociationConfig),
	}
}

func (l *ListenerConfig) associationConfigForAccept(info AcceptInfo) (*AssociationConfig, error) {
	if l == nil {
		return nil, errors.New("nil ListenerConfig")
	}
	selected := l.DefaultAssociationConfig
	if l.SelectAssociationConfig != nil {
		var err error
		selected, err = l.SelectAssociationConfig(info)
		if err != nil {
			return nil, err
		}
	}
	if selected == nil {
		return nil, errors.New("nil AssociationConfig")
	}
	return snapshotAssociationConfig(selected), nil
}

func snapshotAssociationConfig(config *AssociationConfig) *AssociationConfig {
	if config == nil {
		return nil
	}
	snapshot := *config
	if config.HeartbeatInfo != nil {
		heartbeat := *config.HeartbeatInfo
		heartbeat.Data = append([]byte(nil), config.HeartbeatInfo.Data...)
		snapshot.HeartbeatInfo = &heartbeat
	}
	if config.SCTPConfig != nil {
		sctpConfig := *config.SCTPConfig
		if config.SCTPConfig.SCTPSACKInfo != nil {
			sack := *config.SCTPConfig.SCTPSACKInfo
			sctpConfig.SCTPSACKInfo = &sack
		}
		if config.SCTPConfig.SCTPNoDelayInfo != nil {
			noDelay := *config.SCTPConfig.SCTPNoDelayInfo
			sctpConfig.SCTPNoDelayInfo = &noDelay
		}
		snapshot.SCTPConfig = &sctpConfig
	} else {
		snapshot.SCTPConfig = &SCTPConfig{}
	}
	snapshot.ASPIdentifier = config.ASPIdentifier.Copy()
	snapshot.TrafficModeType = config.TrafficModeType.Copy()
	snapshot.NetworkAppearance = config.NetworkAppearance.Copy()
	snapshot.RoutingContexts = config.RoutingContexts.Copy()
	snapshot.CorrelationID = config.CorrelationID.Copy()
	if config.ASPProcedures != nil {
		procedures := *config.ASPProcedures
		snapshot.ASPProcedures = &procedures
	}
	if config.PeerSGP != nil {
		peerSGP := *config.PeerSGP
		snapshot.PeerSGP = &peerSGP
	}
	if config.IPSP != nil {
		ipsp := *config.IPSP
		ipsp.TrafficToLocal = snapshotIPSPTrafficConfig(config.IPSP.TrafficToLocal)
		ipsp.TrafficToPeer = snapshotIPSPTrafficConfig(config.IPSP.TrafficToPeer)
		snapshot.IPSP = &ipsp
	}
	if config.TrafficModes != nil {
		snapshot.TrafficModes = make(map[uint32]uint32, len(config.TrafficModes))
		for routingContext, trafficMode := range config.TrafficModes {
			snapshot.TrafficModes[routingContext] = trafficMode
		}
	}
	return &snapshot
}

func validateAssociationConfigForRole(role Role, config *AssociationConfig) error {
	if config == nil {
		return ErrNilAssociationConfig
	}
	if err := validateASPProcedurePolicy(role, config.ASPProcedures); err != nil {
		return err
	}
	switch role {
	case RoleASP:
		if config.IPSP != nil {
			return fmt.Errorf("%w: IPSP applies only to an IPSP", ErrInvalidRoleConfiguration)
		}
		if config.AuthorizeASP != nil {
			return fmt.Errorf("%w: AuthorizeASP applies only to an SGP", ErrInvalidRoleConfiguration)
		}
	case RoleSGP:
		if config.IPSP != nil {
			return fmt.Errorf("%w: IPSP applies only to an IPSP", ErrInvalidRoleConfiguration)
		}
		if config.ASPIdentifier != nil {
			return fmt.Errorf("%w: ASPIdentifier applies only to an ASP", ErrInvalidRoleConfiguration)
		}
		if config.PeerSGP != nil {
			return fmt.Errorf("%w: PeerSGP applies only to an ASP", ErrInvalidRoleConfiguration)
		}
	case RoleIPSP:
		if config.IPSP == nil {
			return fmt.Errorf("%w: IPSP requires an explicit exchange model", ErrInvalidRoleConfiguration)
		}
		if config.AuthorizeASP != nil {
			return fmt.Errorf("%w: AuthorizeASP applies only to an SGP", ErrInvalidRoleConfiguration)
		}
		if config.PeerSGP != nil {
			return fmt.Errorf("%w: PeerSGP applies only to an ASP", ErrInvalidRoleConfiguration)
		}
		switch config.IPSP.ExchangeModel {
		case IPSPExchangeSingle:
			if config.IPSP.ASPSMExchange != 0 || config.IPSP.TrafficToLocal != nil || config.IPSP.TrafficToPeer != nil {
				return fmt.Errorf("%w: IPSP Single Exchange uses the Association traffic configuration", ErrInvalidRoleConfiguration)
			}
			return nil
		case IPSPExchangeDouble:
			if config.IPSP.ASPSMExchange != IPSPASPSMExchangeDouble &&
				config.IPSP.ASPSMExchange != IPSPASPSMExchangeSingle {
				return fmt.Errorf("%w: IPSP Double Exchange requires an explicit ASPSM exchange agreement", ErrInvalidRoleConfiguration)
			}
			if config.IPSP.TrafficToLocal == nil && config.IPSP.TrafficToPeer == nil {
				return fmt.Errorf("%w: IPSP Double Exchange requires at least one traffic direction", ErrInvalidRoleConfiguration)
			}
			automaticASPSM := config.IPSP.InitiateASPSM
			automaticASPTM := config.IPSP.InitiateASPTM
			if config.ASPProcedures != nil {
				automaticASPSM = config.ASPProcedures.ASPUp == ASPProcedureAutomatic
				automaticASPTM = config.ASPProcedures.ASPActive == ASPProcedureAutomatic
			}
			if config.IPSP.ASPSMExchange == IPSPASPSMExchangeDouble &&
				automaticASPSM && config.IPSP.TrafficToLocal == nil {
				return fmt.Errorf("%w: normal Double Exchange ASPSM initiation requires TrafficToLocal", ErrInvalidRoleConfiguration)
			}
			if automaticASPTM && config.IPSP.TrafficToLocal == nil {
				return fmt.Errorf("%w: automatic ASP Active requires TrafficToLocal", ErrInvalidRoleConfiguration)
			}
			if config.RoutingContexts != nil || config.NetworkAppearance != nil ||
				config.TrafficModeType != nil || len(config.TrafficModes) != 0 {
				return fmt.Errorf("%w: IPSP Double Exchange traffic policy must be directional", ErrInvalidRoleConfiguration)
			}
			if err := validateIPSPTrafficConfig("TrafficToLocal", config.IPSP.TrafficToLocal); err != nil {
				return err
			}
			if err := validateIPSPTrafficConfig("TrafficToPeer", config.IPSP.TrafficToPeer); err != nil {
				return err
			}
			return nil
		default:
			return fmt.Errorf("%w: exchange model %d", ErrUnsupportedIPSPExchangeModel, config.IPSP.ExchangeModel)
		}
	default:
		return ErrUnsupportedRole
	}
	return nil
}

func validateIPSPTrafficConfig(name string, config *IPSPTrafficConfig) error {
	if config == nil {
		return nil
	}
	if err := validateIPSPTrafficParam(name, "TrafficModeType", config.TrafficModeType, params.TrafficModeType); err != nil {
		return err
	}
	if err := validateIPSPTrafficParam(name, "NetworkAppearance", config.NetworkAppearance, params.NetworkAppearance); err != nil {
		return err
	}
	if err := validateIPSPTrafficParam(name, "RoutingContexts", config.RoutingContexts, params.RoutingContext); err != nil {
		return err
	}

	configuredRoutingContexts := make(map[uint32]struct{})
	if config.RoutingContexts != nil {
		for _, routingContext := range config.RoutingContexts.RoutingContexts() {
			if _, duplicate := configuredRoutingContexts[routingContext]; duplicate {
				return fmt.Errorf("%w: %s contains duplicate Routing Context %d",
					ErrInvalidRoleConfiguration, name, routingContext)
			}
			configuredRoutingContexts[routingContext] = struct{}{}
		}
	}
	for routingContext, trafficMode := range config.TrafficModes {
		if !validTrafficMode(trafficMode) {
			return fmt.Errorf("%w: %s has undefined Traffic Mode %d for Routing Context %d",
				ErrInvalidRoleConfiguration, name, trafficMode, routingContext)
		}
		if _, configured := configuredRoutingContexts[routingContext]; !configured {
			return fmt.Errorf("%w: %s has a Traffic Mode for unconfigured Routing Context %d",
				ErrInvalidRoleConfiguration, name, routingContext)
		}
	}
	return nil
}

func validateIPSPTrafficParam(direction, name string, parameter *params.Param, wantTag uint16) error {
	if parameter == nil {
		return nil
	}
	if parameter.Tag != wantTag {
		return fmt.Errorf("%w: %s %s has parameter tag %#04x, want %#04x",
			ErrInvalidRoleConfiguration, direction, name, parameter.Tag, wantTag)
	}
	if _, err := parameter.Copy().MarshalBinary(); err != nil {
		return fmt.Errorf("%w: %s %s: %v", ErrInvalidRoleConfiguration, direction, name, err)
	}
	return nil
}

func snapshotIPSPTrafficConfig(config *IPSPTrafficConfig) *IPSPTrafficConfig {
	if config == nil {
		return nil
	}
	snapshot := *config
	snapshot.TrafficModeType = config.TrafficModeType.Copy()
	snapshot.NetworkAppearance = config.NetworkAppearance.Copy()
	snapshot.RoutingContexts = config.RoutingContexts.Copy()
	if config.TrafficModes != nil {
		snapshot.TrafficModes = make(map[uint32]uint32, len(config.TrafficModes))
		for routingContext, trafficMode := range config.TrafficModes {
			snapshot.TrafficModes[routingContext] = trafficMode
		}
	}
	return &snapshot
}

func newAcceptInfo(local, remote net.Addr) AcceptInfo {
	return AcceptInfo{
		LocalAddr:  cloneSCTPAddrFromNetAddr(local),
		RemoteAddr: cloneSCTPAddrFromNetAddr(remote),
	}
}

func cloneSCTPAddrFromNetAddr(addr net.Addr) *sctp.SCTPAddr {
	sctpAddr, ok := addr.(*sctp.SCTPAddr)
	if !ok {
		return nil
	}
	return cloneSCTPAddr(sctpAddr)
}

func cloneSCTPAddr(addr *sctp.SCTPAddr) *sctp.SCTPAddr {
	if addr == nil {
		return nil
	}
	clone := &sctp.SCTPAddr{Port: addr.Port}
	if len(addr.IPAddrs) > 0 {
		clone.IPAddrs = make([]net.IPAddr, len(addr.IPAddrs))
		for index, ipAddr := range addr.IPAddrs {
			clone.IPAddrs[index] = net.IPAddr{
				IP:   append(net.IP(nil), ipAddr.IP...),
				Zone: ipAddr.Zone,
			}
		}
	}
	return clone
}

// NewAssociationConfig creates a role-neutral M3UA association configuration.
//
// To set additional parameters, use constructors in param package or
// setters defined in this package. Note that the params left nil won't
// appear in the packets but the initialized params will, with zero
// values.
func NewAssociationConfig(
	originatingPointCode,
	destinationPointCode uint32,
	serviceIndicator,
	networkIndicator,
	messagePriority,
	signallingLinkSelection uint8,
) *AssociationConfig {
	return &AssociationConfig{
		SCTPConfig:              &SCTPConfig{},
		OriginatingPointCode:    originatingPointCode,
		DestinationPointCode:    destinationPointCode,
		ServiceIndicator:        serviceIndicator,
		NetworkIndicator:        networkIndicator,
		MessagePriority:         messagePriority,
		SignallingLinkSelection: signallingLinkSelection,
	}
}

// EnableHeartbeat enables RFC 4666 M3UA BEAT with the given interval and
// expiration timer.
//
// It does not enable, disable, or tune SCTP HEARTBEAT chunks; SCTP heartbeat
// behavior remains transport/kernel behavior.
//
// Each BEAT carries freshly generated random Heartbeat Data, and the BEAT
// Ack's echo is validated against it, so BEAT/BEAT Ack pairs identify
// themselves; the HeartbeatInfo.Data field does not influence the exchange.
func (c *AssociationConfig) EnableHeartbeat(interval, timer time.Duration) *AssociationConfig {
	c.HeartbeatInfo = NewHeartbeatInfo(
		interval, timer,
		[]byte("Hi, this is a BEAT from go-m3ua. Are you alive?"),
	)
	return c
}

// SetSCTPSACK sets the SCTP SACK timer configuration.
//
// sackDelay is the number of milliseconds for the delayed SACK timer. RFC 9260
// Section 6.2 allows any value up to 500 ms and forbids more. This setter is
// chainable and has no way to report that, so a larger value is refused when
// the association is set up, and Dial or Accept fails with ErrSackDelayTooLarge.
//
// sackFrequency is the number of packets to receive before sending a SACK
// without waiting for the delay timer. Setting to 1 disables the delayed
// SACK algorithm.
//
// Note: sackDelay=0, sackFrequency=1 (disables delayed SACK)
func (c *AssociationConfig) SetSCTPSACK(sackDelay, sackFrequency uint32) *AssociationConfig {
	if c.SCTPConfig == nil {
		c.SCTPConfig = &SCTPConfig{}
	}
	c.SCTPConfig.SCTPSACKInfo = &SCTPSACKInfo{
		Enabled:       true,
		SackDelay:     sackDelay,
		SackFrequency: sackFrequency,
	}
	return c
}

// SetSCTPNoDelay sets the SCTP_NODELAY option.
//
// When noDelay is true, the Nagle-like bundling algorithm is disabled and
// user messages are sent as soon as possible. When false, small messages
// may be bundled to improve throughput.
func (c *AssociationConfig) SetSCTPNoDelay(noDelay bool) *AssociationConfig {
	if c.SCTPConfig == nil {
		c.SCTPConfig = &SCTPConfig{}
	}
	c.SCTPConfig.SCTPNoDelayInfo = &SCTPNoDelayInfo{
		Enabled: true,
		NoDelay: noDelay,
	}
	return c
}

// SetASPIdentifier sets the optional RFC 4666 ASP Identifier parameter.
func (c *AssociationConfig) SetASPIdentifier(id uint32) *AssociationConfig {
	c.ASPIdentifier = params.NewAspIdentifier(id)
	return c
}

// SetTrafficModeType sets the RFC 4666 Traffic Mode Type parameter.
func (c *AssociationConfig) SetTrafficModeType(trafficMode uint32) *AssociationConfig {
	c.TrafficModeType = params.NewTrafficModeType(trafficMode)
	return c
}

// SetNetworkAppearance sets the RFC 4666 Network Appearance parameter.
func (c *AssociationConfig) SetNetworkAppearance(networkAppearance uint32) *AssociationConfig {
	c.NetworkAppearance = params.NewNetworkAppearance(networkAppearance)
	return c
}

// SetRoutingContexts sets the RFC 4666 Routing Context parameter.
func (c *AssociationConfig) SetRoutingContexts(routingContexts ...uint32) *AssociationConfig {
	c.RoutingContexts = params.NewRoutingContext(routingContexts...)
	return c
}

// SetCorrelationID sets the RFC 4666 Correlation ID parameter.
func (c *AssociationConfig) SetCorrelationID(id uint32) *AssociationConfig {
	c.CorrelationID = params.NewCorrelationID(id)
	return c
}
