// Copyright 2018-2024 go-m3ua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package m3ua

import (
	"net"
	"time"

	"github.com/gomaja/go-m3ua/messages/params"
)

// HeartbeatInfo is a set of information for M3UA BEAT.
type HeartbeatInfo struct {
	Enabled  bool
	Interval time.Duration
	Timer    time.Duration
	Data     []byte
}

// NewHeartbeatInfo creates a new HeartbeatInfo.
func NewHeartbeatInfo(interval, timer time.Duration, data []byte) *HeartbeatInfo {
	return &HeartbeatInfo{
		Enabled: true, Interval: interval, Timer: timer, Data: data,
	}
}

// SctpSackInfo is a set of information for SCTP SACK timer configuration.
//
// SackDelay sack_delay: This parameter contains the number of milliseconds the
// user is requesting that the delayed SACK timer be set to.
//
// RFC 9260 Section 6.2 — the current SCTP specification, which obsoleted
// RFC 4960 — bounds it from above only: "An implementation MUST NOT allow the
// maximum delay (protocol parameter 'SACK.Delay') to be configured to be more
// than 500 ms. In other words, an implementation MAY lower the value of
// 'SACK.Delay' below 500 ms but MUST NOT raise it above 500 ms." The 200 ms in
// the same section is when an acknowledgement SHOULD be generated by, not a
// floor, so any value up to 500 is permitted and zero disables the delay.
// A larger value is refused when the association is set up; see
// ErrSackDelayTooLarge.
//
// SackFrequency sack_freq: This parameter contains the number of packets that must
// be received before a SACK is sent without waiting for the delay
// timer to expire.  The default value is 2; setting this value to 1
// will disable the delayed SACK algorithm.
type SctpSackInfo struct {
	Enabled       bool
	SackDelay     uint32
	SackFrequency uint32
}

// SctpNoDelayInfo is a set of information for SCTP NODELAY configuration.
//
// NoDelay, when true, disables the Nagle-like bundling algorithm so that
// user messages are sent as soon as possible (SCTP_NODELAY = 1). When
// false, small messages may be bundled to improve throughput.
type SctpNoDelayInfo struct {
	Enabled bool
	NoDelay bool
}

// DefaultReadBufferSize is the read buffer size used when SCTPConfig
// leaves ReadBufferSize unset.
//
// 64 KiB accommodates any M3UA message in practical use — SS7 traffic
// interworked at an SG is capped at a 272-octet SIF, and even the larger blocks
// M3UA permits natively stay far below this — while costing one allocation per
// association rather than per read.
const DefaultReadBufferSize = 65535

// SCTPConfig holds all SCTP-related configuration parameters.
// This separates SCTP layer configuration from M3UA layer configuration.
//
// A Config — and so this SCTPConfig — may be shared by every Conn a Listener
// accepts, and by repeated Dials. It therefore holds settings only: the
// association itself and everything derived from it belong to the Conn.
type SCTPConfig struct {
	*SctpSackInfo
	*SctpNoDelayInfo

	// InitTimeout bounds Dial's one-shot SCTP association attempt. Zero
	// selects DefaultInitTimeout.
	InitTimeout time.Duration

	// ReadBufferSize is the size of the buffer each read from the association
	// is made into. Zero selects DefaultReadBufferSize.
	//
	// SCTP reassembles a fragmented message before delivering it, so this is
	// not an MTU: it must accommodate the largest single M3UA message a peer
	// may send. RFC 4666 Section 1.3.2.1 is explicit that "The M3UA layer does
	// not impose a 272-octet signalling information field (SIF) length limit
	// as specified by the SS7 MTP Level 2 protocol. Larger information blocks
	// can be accommodated directly by M3UA/SCTP", and the message length field
	// is 32-bit, so there is no protocol-level maximum to size against. Raise
	// this if a peer is known to send larger blocks than the default allows.
	ReadBufferSize int
}

// DefaultInitTimeout bounds one SCTP association attempt: how long Dial waits
// for the INIT-ACK before giving up and releasing the socket.
//
// Dial makes at most one attempt and never retries; a caller that wants to keep
// trying loops over Dial and chooses its own cadence. Left to the kernel, the
// attempt runs to net.sctp.max_init_retransmits with the RTO doubling from
// net.sctp.rto_initial to net.sctp.rto_max — measured at nine INIT chunks over
// 342 seconds on Linux defaults, which is far too long for an application to
// react to anything.
//
// Dial enforces the one-shot contract per socket by raising SCTP_RTOINFO's
// Initial and Max values beyond this budget before connecting. If no INIT-ACK
// arrives before the timeout, Dial returns ErrInitTimeout; if ctx is cancelled
// first, Dial quietly abandons the in-flight socket promptly and returns
// ctx.Err().
const DefaultInitTimeout = 5 * time.Second

// DefaultEstablishTimeout bounds the M3UA handshake once the association is up:
// how long Dial and Accept wait to reach ASP-ACTIVE.
const DefaultEstablishTimeout = 10 * time.Second

// DefaultDataQueueSize is the number of inbound DATA messages one association
// retains while its application is not reading. It is large enough to absorb
// ordinary traffic bursts without the 65,535-slot allocation every Conn used
// to make; sustained overflow remains non-blocking and reports local congestion.
const DefaultDataQueueSize = 1024

// DefaultRecoveryQueueMessages bounds how many outbound DATA messages an SGP
// retains while an Application Server is AS-PENDING. RFC 4666 Section 4.3.2
// recommends queuing during T(r), but an unbounded queue lets a failed AS
// exhaust the process before recovery can complete.
const DefaultRecoveryQueueMessages = 1024

// DefaultRecoveryQueueBytes bounds the encoded size of the DATA messages held
// for one AS during T(r). The count limit alone is insufficient because M3UA
// deliberately permits payloads larger than an SS7 MTP2 SIF.
const DefaultRecoveryQueueBytes = 4 << 20

// DefaultRecoveryQueueTotalMessages bounds recovery DATA retained across all
// Application Servers owned by one Listener.
const DefaultRecoveryQueueTotalMessages = 4096

// DefaultRecoveryQueueTotalBytes is the listener-wide encoded DATA budget.
const DefaultRecoveryQueueTotalBytes = 16 << 20

// DefaultBroadcastFlowCacheEntries bounds synchronization markers retained for
// one Broadcast AS. Eviction can only cause an extra Correlation ID to be sent.
const DefaultBroadcastFlowCacheEntries = 4096

// DefaultBroadcastFlowIdentifierBytes bounds the application-defined portion
// of a retained Broadcast flow key.
const DefaultBroadcastFlowIdentifierBytes = 256

// DefaultTAckRetries is how many times an unacknowledged ASPSM/ASPTM request is
// resent before the attempt is reported as failed.
//
// RFC 4666 says to resend "until it receives the Ack", which is unbounded; a
// bound turns a peer that will never answer into a reportable error instead of
// an indefinite silent retry against a network already in trouble.
const DefaultTAckRetries = 5

// BroadcastFlowIdentifier adds application semantics to the default Broadcast
// traffic-flow key. The library already keys by Network Appearance, Routing
// Context, and the complete MTP3 routing label. Applications may return, for
// example, an ISUP CIC or SCCP subsystem discriminator when independently
// sequenced flows share that label. The callback receives an owned copy and
// must return a stable identifier for equivalent flows.
type BroadcastFlowIdentifier func(*params.ProtocolDataPayload) (string, error)

// ASPIdentity identifies an ASP at the point its ASP Up is received. The ASP
// Identifier is optional in RFC 4666, so ASPIdentifierSet distinguishes an
// omitted identifier from the valid value zero. RemoteAddr is nil for a Conn
// constructed without a live SCTP association.
type ASPIdentity struct {
	ASPIdentifier    uint32
	ASPIdentifierSet bool
	RemoteAddr       net.Addr
}

// ASPAuthorizer returns the Routing Contexts an accepted ASP is configured to
// serve. The result is copied and must be a subset of Config.RoutingContexts.
// Returning an empty slice authorizes no Application Server. The decision is
// resolved once at ASP Up and remains immutable for that association.
type ASPAuthorizer func(ASPIdentity) []uint32

// Config is a configuration that defines a M3UA server.
type Config struct {
	*HeartbeatInfo
	*SCTPConfig
	// TAck is the T(ack) timer: how long to wait for an ASPSM/ASPTM
	// acknowledgement before resending the request. Zero selects DefaultTAck
	// (2 seconds, per RFC 4666 Sections 4.3.4.1 to 4.3.4.4).
	TAck time.Duration
	// TAckRetries bounds how many times a request is resent before the attempt
	// is reported as failed. Zero selects DefaultTAckRetries.
	TAckRetries int
	// EstablishTimeout bounds the M3UA handshake once the association is up.
	// Zero selects DefaultEstablishTimeout.
	EstablishTimeout time.Duration
	// DataQueueSize is the maximum number of inbound DATA messages retained for
	// Read, ReadPD, or ReadData. Values less than or equal to zero select
	// DefaultDataQueueSize. Once full, further DATA is discarded and local
	// congestion is reported without blocking the association dispatcher.
	DataQueueSize int
	AspIdentifier *params.Param
	// TrafficModeType is the default traffic-handling mode. Its value is copied
	// when a Conn or Listener is constructed; later mutations do not alter
	// established protocol policy.
	TrafficModeType *params.Param
	// AuthorizeASP optionally narrows the listener-wide Routing Context inventory
	// to the immutable set this peer may serve. Without it, accepted ASPs retain
	// the legacy policy of being configured for every Routing Context.
	AuthorizeASP ASPAuthorizer
	// TrafficModes optionally configures Traffic Mode per Routing Context. It
	// takes precedence over TrafficModeType and permits one association to serve
	// ASes with different modes. Values must be Override, Loadshare, or Broadcast.
	// The map is copied when a Conn or Listener is constructed.
	TrafficModes      map[uint32]uint32
	NetworkAppearance *params.Param
	// RecoveryTimer is T(r), the AS-PENDING recovery timer of RFC 4666
	// Section 4.3.2: "A recovery timer T(r) SHOULD be started, and all incoming
	// signalling messages SHOULD be queued by the SGP.  If an ASP becomes
	// ASP-ACTIVE before T(r) expires, the AS is moved to the AS-ACTIVE state".
	//
	// Zero selects DefaultRecoveryTimer. Server-side only: the AS state machine
	// is maintained on the SGP.
	RecoveryTimer time.Duration
	// RecoveryQueueMessages and RecoveryQueueBytes bound the DATA retained for
	// an AS while T(r) runs. Values less than or equal to zero select the
	// corresponding defaults. Both limits apply; reaching either refuses the
	// new message without disturbing traffic already queued.
	RecoveryQueueMessages int
	RecoveryQueueBytes    int
	// RecoveryQueueTotalMessages and RecoveryQueueTotalBytes cap the aggregate
	// queued plus in-flight recovery traffic across every AS on the Listener.
	// Values less than or equal to zero select the corresponding defaults.
	RecoveryQueueTotalMessages int
	RecoveryQueueTotalBytes    int
	// BroadcastFlowIdentifier optionally refines the default routing-label flow
	// key used for RFC 4666 Broadcast synchronization Correlation IDs. It is
	// snapshotted when the Listener first accepts an association.
	BroadcastFlowIdentifier BroadcastFlowIdentifier
	// BroadcastFlowCacheEntries bounds remembered flows per AS. Values less than
	// or equal to zero select DefaultBroadcastFlowCacheEntries. On overflow the
	// cache is cleared, which safely produces extra synchronization markers.
	BroadcastFlowCacheEntries int
	// BroadcastFlowIdentifierBytes bounds the identifier returned by
	// BroadcastFlowIdentifier. Values less than or equal to zero select the
	// default. Oversized identifiers are rejected rather than truncated.
	BroadcastFlowIdentifierBytes int
	// Compatibility configures explicit receive-side tolerance for known peer
	// protocol violations. The zero value keeps RFC-strict behaviour.
	Compatibility CompatibilityPolicy

	RoutingContexts        *params.Param
	CorrelationID          *params.Param
	OriginatingPointCode   uint32
	DestinationPointCode   uint32
	ServiceIndicator       uint8
	NetworkIndicator       uint8
	MessagePriority        uint8
	SignalingLinkSelection uint8
}

// NewConfig creates a new Config.
//
// To set additional parameters, use constructors in param package or
// setters defined in this package. Note that the params left nil won't
// appear in the packets but the initialized params will, with zero
// values.
func NewConfig(opc, dpc uint32, si, ni, mp, sls uint8) *Config {
	return &Config{
		SCTPConfig:             &SCTPConfig{},
		OriginatingPointCode:   opc,
		DestinationPointCode:   dpc,
		ServiceIndicator:       si,
		NetworkIndicator:       ni,
		MessagePriority:        mp,
		SignalingLinkSelection: sls,
	}
}

// EnableHeartbeat enables M3UA BEAT with interval and expiration timer
// given.
//
// Each BEAT carries freshly generated random Heartbeat Data, and the BEAT
// Ack's echo is validated against it, so BEAT/BEAT Ack pairs identify
// themselves; the HeartbeatInfo.Data field does not influence the exchange.
func (c *Config) EnableHeartbeat(interval, timer time.Duration) *Config {
	c.HeartbeatInfo = NewHeartbeatInfo(
		interval, timer,
		[]byte("Hi, this is a BEAT from go-m3ua. Are you alive?"),
	)
	return c
}

// SetSackConfig sets the SCTP SACK timer configuration.
//
// sackDelay is the number of milliseconds for the delayed SACK timer. RFC 9260
// Section 6.2 allows any value up to 500 ms and forbids more. This setter is
// chainable and has no way to report that, so a larger value is refused when
// the association is set up, and Dial or Accept fails with ErrSackDelayTooLarge.
//
// sackFrequency is the number of packets to receive before sending a SACK
// without waiting for the delay timer. Setting to 1 disables the delayed
// SACK algorithm.
//
// Note: sackDelay=0, sackFrequency=1 (disables delayed SACK)
func (c *Config) SetSackConfig(sackDelay, sackFrequency uint32) *Config {
	if c.SCTPConfig == nil {
		c.SCTPConfig = &SCTPConfig{}
	}
	c.SCTPConfig.SctpSackInfo = &SctpSackInfo{
		Enabled:       true,
		SackDelay:     sackDelay,
		SackFrequency: sackFrequency,
	}
	return c
}

// SetNoDelayConfig sets the SCTP_NODELAY option.
//
// When noDelay is true, the Nagle-like bundling algorithm is disabled and
// user messages are sent as soon as possible. When false, small messages
// may be bundled to improve throughput.
func (c *Config) SetNoDelayConfig(noDelay bool) *Config {
	if c.SCTPConfig == nil {
		c.SCTPConfig = &SCTPConfig{}
	}
	c.SCTPConfig.SctpNoDelayInfo = &SctpNoDelayInfo{
		Enabled: true,
		NoDelay: noDelay,
	}
	return c
}

// SetAspIdentifier sets AspIdentifier in Config.
func (c *Config) SetAspIdentifier(id uint32) *Config {
	c.AspIdentifier = params.NewAspIdentifier(id)
	return c
}

// SetTrafficModeType sets TrafficModeType in Config.
func (c *Config) SetTrafficModeType(tmType uint32) *Config {
	c.TrafficModeType = params.NewTrafficModeType(tmType)
	return c
}

// SetNetworkAppearance sets NetworkAppearance in Config.
func (c *Config) SetNetworkAppearance(nwApr uint32) *Config {
	c.NetworkAppearance = params.NewNetworkAppearance(nwApr)
	return c
}

// SetRoutingContexts sets RoutingContexts in Config.
func (c *Config) SetRoutingContexts(rtCtxs ...uint32) *Config {
	c.RoutingContexts = params.NewRoutingContext(rtCtxs...)
	return c
}

// SetCorrelationID sets CorrelationID in Config.
func (c *Config) SetCorrelationID(id uint32) *Config {
	c.CorrelationID = params.NewCorrelationID(id)
	return c
}

// NewClientConfig creates a new Config for Client.
//
// The optional parameters that is not required (like CorrelationID)
// can be omitted by setting it to nil after created *Config.
func NewClientConfig(hbInfo *HeartbeatInfo, opc, dpc, aspID, tmt, nwApr, corrID uint32, rtCtxs []uint32, si, ni, mp, sls uint8) *Config {
	return &Config{
		HeartbeatInfo:          hbInfo,
		SCTPConfig:             &SCTPConfig{},
		AspIdentifier:          params.NewAspIdentifier(aspID),
		TrafficModeType:        params.NewTrafficModeType(tmt),
		NetworkAppearance:      params.NewNetworkAppearance(nwApr),
		RoutingContexts:        params.NewRoutingContext(rtCtxs...),
		CorrelationID:          params.NewCorrelationID(corrID),
		OriginatingPointCode:   opc,
		DestinationPointCode:   dpc,
		ServiceIndicator:       si,
		NetworkIndicator:       ni,
		MessagePriority:        mp,
		SignalingLinkSelection: sls,
	}
}

// NewServerConfig creates a new Config for Server.
//
// The optional parameters that is not required (like CorrelationID)
// can be omitted by setting it to nil after created *Config.
func NewServerConfig(hbInfo *HeartbeatInfo, opc, dpc, aspID, tmt, nwApr, corrID uint32, rtCtxs []uint32, si, ni, mp, sls uint8) *Config {
	return &Config{
		HeartbeatInfo:          hbInfo,
		SCTPConfig:             &SCTPConfig{},
		AspIdentifier:          params.NewAspIdentifier(aspID),
		TrafficModeType:        params.NewTrafficModeType(tmt),
		NetworkAppearance:      params.NewNetworkAppearance(nwApr),
		RoutingContexts:        params.NewRoutingContext(rtCtxs...),
		CorrelationID:          params.NewCorrelationID(corrID),
		OriginatingPointCode:   opc,
		DestinationPointCode:   dpc,
		ServiceIndicator:       si,
		NetworkIndicator:       ni,
		MessagePriority:        mp,
		SignalingLinkSelection: sls,
	}
}
