// Copyright 2018-2024 go-m3ua authors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package m3ua

import (
	"context"
	"errors"
	"fmt"
	"testing"
	"time"

	"github.com/gomaja/go-m3ua/messages/params"
	"github.com/gomaja/go-sctp"
)

// RFC 9260 Section 6.2, the current SCTP specification:
//
//	An implementation MUST NOT allow the maximum delay (protocol parameter
//	'SACK.Delay') to be configured to be more than 500 ms.  In other words,
//	an implementation MAY lower the value of 'SACK.Delay' below 500 ms but
//	MUST NOT raise it above 500 ms.
//
// The value went to setsockopt unchecked. Linux happens to enforce the ceiling
// itself — 500 is accepted, 501 returns EINVAL — so on that stack the refusal
// arrived as "failed to set sack timer: invalid argument": opaque, unmatched by
// any exported error, and owed to the host rather than to this package. The rule
// is the specification's, so it is checked here and reported as itself.
//
// The package's own documentation described the range as "between 200 and 500
// ms", which is not what either RFC 9260 or the RFC 4960 it obsoleted says:
// 200 ms is when an acknowledgement SHOULD be generated by, not a floor, and the
// same doc comment went on to recommend zero to disable the delay.
func TestSackDelayIsBoundedByTheSpecification(t *testing.T) {
	for _, tc := range []struct {
		name  string
		delay uint32
		ok    bool
	}{
		{"zero disables the delay", 0, true},
		{"below the 200 ms target is permitted", 50, true},
		{"the 200 ms target itself", 200, true},
		{"one below the ceiling", 499, true},
		{"the ceiling itself is allowed", 500, true},
		{"one millisecond above the ceiling is refused", 501, false},
		{"a full second is refused", 1000, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			err := validateSackDelay(tc.delay)
			if tc.ok && err != nil {
				t.Errorf("validateSackDelay(%d) = %v, want nil", tc.delay, err)
			}
			if !tc.ok {
				if err == nil {
					t.Fatalf("validateSackDelay(%d) = nil; the association would "+
						"be configured beyond the 500 ms ceiling", tc.delay)
				}
				if !errors.Is(err, ErrSackDelayTooLarge) {
					t.Errorf("error = %v, want ErrSackDelayTooLarge", err)
				}
			}
		})
	}
}

// The Config setter is chainable and cannot report the refusal itself, so it
// has to survive the value and let the association fail. This pins that it
// stores what it was given rather than clamping silently.
func TestSackConfigStoresTheValueForValidationLater(t *testing.T) {
	cfg := (&Config{}).SetSackConfig(750, 2)

	if cfg.SctpSackInfo == nil {
		t.Fatal("SetSackConfig stored nothing")
	}
	if cfg.SctpSackInfo.SackDelay != 750 {
		t.Errorf("SackDelay = %d, want 750 stored unchanged; a silent clamp "+
			"would apply a timer the caller never asked for",
			cfg.SctpSackInfo.SackDelay)
	}
	if err := validateSackDelay(cfg.SctpSackInfo.SackDelay); !errors.Is(err, ErrSackDelayTooLarge) {
		t.Errorf("the stored value validates as %v, want ErrSackDelayTooLarge", err)
	}
}

// The refusal has to happen on the association the Config is applied to, not
// only in the helper: setUpSocket is where the value reaches setsockopt, and it
// is the last point at which a non-conformant timer can be stopped.
func TestDialRefusesASackDelayAboveTheCeiling(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	const port = 3217
	newCfg := func() *Config {
		return NewClientConfig(
			&HeartbeatInfo{Enabled: false},
			0x11111111, 0x22222222, 1, params.TrafficModeLoadshare, 0, 0,
			[]uint32{1}, params.ServiceIndSCCP, 0, 0, 1,
		)
	}

	srvAddr, err := sctp.ResolveSCTPAddr("sctp", fmt.Sprintf("127.0.0.2:%d", port))
	if err != nil {
		t.Fatal(err)
	}
	ln, err := Listen("m3ua", srvAddr, newCfg())
	if err != nil {
		if isSCTPUnsupported(err) {
			t.Skipf("skipping socket-backed test: %v", err)
		}
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = ln.Close() })
	accepted := make(chan *Conn, 2)
	go func() {
		for {
			c, err := ln.Accept(ctx)
			if err != nil {
				return
			}
			select {
			case accepted <- c:
			case <-ctx.Done():
				_ = c.Close()
				return
			}
		}
	}()

	// 500 ms is the ceiling and must still establish.
	okCfg := newCfg().SetSackConfig(500, 2)
	conn, err := Dial(ctx, "m3ua", nil, srvAddr, okCfg)
	if err != nil {
		t.Fatalf("Dial with the permitted 500 ms ceiling failed: %v", err)
	}
	okConn := conn
	defer func() { _ = okConn.Close() }()
	select {
	case serverConn := <-accepted:
		defer func() { _ = serverConn.Close() }()
	case <-time.After(5 * time.Second):
		t.Fatal("server never accepted the permitted SACK delay association")
	}

	// One millisecond more is not configurable, so the association must not be.
	badCfg := newCfg().SetSackConfig(501, 2)
	conn, err = Dial(ctx, "m3ua", nil, srvAddr, badCfg)
	if err == nil {
		_ = conn.Close()
		t.Fatal("Dial accepted a SACK delay above the 500 ms ceiling and " +
			"configured the association with it")
	}
	if !errors.Is(err, ErrSackDelayTooLarge) {
		t.Errorf("Dial error = %v, want ErrSackDelayTooLarge", err)
	}
}
